### Creat a user
POST http://localhost:9090/idcheck/users
content-type: application/json

{
    "idnew_table": 5,
    "name": "Rimas",
    "NIC": "123456789V",
    "Address": "Colombo",
}

### Get users
GET http://localhost:9090/checkNic/123455678V

### Get a specific user
GET http://localhost:9090/idcheck/users/1